### ISSUE TITLE
`get-in` bug

### ISSUE THREAD

**Issue by soulawaker** [janet-lang/janet#751] opened 2021-08-04 06:56 UTC
```clojure
$ (def t2 {:side false})
{:side false}
$ (get-in t2 [:side :note])
false #; I expected nil
$ (get-in t2 [:side :note] "dflt")
false #; not "dflt"
```

**Comment by pepe** [comment] 2021-08-04 08:36
It indeed is unexpected behavior caused by `false`. @sogaiu's version is right.

**Comment by sogaiu** [comment] 2021-08-04 11:35
Not sure I follow what you mean, but IIRC, janet's tables and structs are like Lua's in the sense that:
```
repl:1:> (def t @{:a 1})
@{:a 1}
repl:2:> (put t :a nil)
@{}
repl:3:> t
@{}
```
Or as Lua's [Tables Tutorial](http://lua-users.org/wiki/TablesTutorial) says:
> You can erase a key/value pair from a table by assigning nil to the value.

**Comment by bakpakin** [comment] 2021-08-06 21:15
Fixed, closing.

**Closed** 2021-08-07 06:03 UTC
