### ISSUE TITLE
Build failure on openbsd sparc64

### ISSUE THREAD

**Issue by jturner** [janet-lang/janet#171] opened 2019-10-15 14:03 UTC
janet fails to build on openbsd sparc64 with `compile error in boot.janet: (macro) expected integer key`. Full build log available here: http://build-failures.rhaalovely.net//sparc64/2019-10-11/lang/janet.log

**Comment by bakpakin** [comment] 2019-10-15 17:41
First, thanks for helping with Sparc, as that is a difficult platform for me to test.

One thing is to make sure that Janet is not trying to use nanboxing. You can force nanboxing off by uncommenting `#define JANET_NO_NANBOX` in `src/conf/janetconf.janet`. Nanbox should be disabled by default on this platform, but faulty nanboxing does cause this kind of error.

If that doesn't work, I think I will need more than just the build logs above. Is valgrind supported on sparc64, openbsd? I would be curious to see the result of 

```
valgrind build/janet_boot build/core_image.c JANET_PATH '/usr/local/lib/janet' JANET_HEADERPATH '/usr/local/include/janet'
```

Janet SHOULD be valgrind clean, so any memory issues or undefined behavior may be a red flag. Adding the -g option to the Makefile would also help here.

I think that errors from inside macros could be clearer, but I have a feeling that the error came from the first macro invocation in `src/boot/boot.janet`, and indicates a much deeper underlying problem.

**Comment by bakpakin** [comment] 2020-01-06 04:17
Closing for now, as the current Janet version has progressed far since this issue was filed. If reproduced with a newer version, may reopen.

**Closed** 2020-01-06 04:18 UTC
Labels: bug
