### ISSUE TITLE
net/server backpressure

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#359] opened 2020-04-28 07:07 UTC
The api could use a way to prevent accepting of incoming connections when the application detects overload, otherwise the server will continue accepting new connections until memory or file descriptors are exhausted, especially in high load situations.

I am unsure how this would look in a callback based api.

**Comment by bakpakin** [comment] 2020-04-28 18:27
Yes this is something that does need to be added to the api. My thought is to have an optional predicate that would check incoming connection information and accept or not. If this predicate was also async, one could have back pressure.

**Comment by andrewchambers** [comment] 2020-04-29 07:09
Oh, we also need a way to shutdown gracefully at request I suppose.

**Comment by bakpakin** [comment] 2020-05-01 01:31
Servers can be shutdown with `(:close net/server-return-value)` - servers are themselves stream (although not readable streams). In that regard, we could also consider a server without a handler to behave like a more traditional unix socket server (accepting in a loop) and make them readable streams in that case.

**Comment by andrewchambers** [comment] 2020-05-01 02:02
Sure, if you go that route, net/listen and net/accept don't seem that bad. My main experience is the with Go api. net/server definitely seems quite nice for convenience.

**Comment by bakpakin** [comment] 2020-08-04 01:18
This is addressed in the `ev` branch, but has not yet been merged into master. See `examples/tcpserver.janet` in that branch for an example that doesn't use an explicit connection handler.

**Comment by andrewchambers** [comment] 2020-08-04 01:47
Random note:

I noticed something that Pony does with actors, (Basically their version of channels), is de prioritize the thread of control sending to a clogged queue. Not sure if that has any place with janet, but just a note.

**Comment by bakpakin** [comment] 2020-08-04 02:24
Might be good to consider, but channels are still a WIP, not sure If the final implementation will change. Currrently, blocked channels are not even added to the global scheduler so their is not IO penalty for having many blocked channels - in fact, since channels all live in the same thread (for now), there is no need for IO or any kind of polling for channel communication, at least with the current implementation. There are some downsides to this (perhaps slightly more memory usage in some cases, some attention may be needed for scheduling fairness), and some other unexpected behaviors. These can be worked around, but generally I think it's good for reading from a channel to be as light as possible.

**Closed** 2021-01-24 23:37 UTC
