### ISSUE TITLE
Feature request: Add janet to list of github languages

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#146] opened 2019-07-25 14:13 UTC
https://github.com/github/linguist/blob/master/CONTRIBUTING.md

It would be nice if projects using janet / .janet files showed up in the metric bar on github.

Also - this repo shows clojure in use in the metric bar - I wonder why?

**Comment by bakpakin** [comment] 2019-07-25 16:00
Simply to use clojure syntax highlighting on GitHub for Janet files - makes things look nice. It would be great to contribute a grammar to linguist, but I’m not sure janet quite meets the requirements for a language to be included in linguist (although they are quite inclusive, so maybe they will).

**Comment by ahungry** [comment] 2019-07-25 16:13
Neat, I didn't know about that - very nice.

**Comment by rduplain** [comment] 2019-09-14 18:00
Preface: I'm commenting as a casual observer, not a Linguist contributor.

[The Linguist guideline says](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) "In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist."

> I’m not sure janet quite meets the requirements for a language to be included in linguist (although they are quite inclusive, so maybe they will).

As of today, GitHub search shows [247 code results for .janet files](https://github.com/search?q=extension%3Ajanet+NOT+nothack&type=Code). This 247 number indicates _files_. There appears to be no way to view code extensions by _repository_, so these code results would need a few hundred more to show the likelihood of "hundreds of repositories."

That said, there are precedents with <2k code results (example: MLIR grammar in pull request \#4610) and Janet repositories can remain very small, ~2 .janet files for a complete project (project.janet and a source file). Further, 800+ :octocat: stars on Janet supports evidence of a growing community.

Looking at recent Linguist pull requests, a successful Janet addition appears likely.

**Comment by bakpakin** [comment] 2019-10-13 05:37
Well, seems unlikely in the near future. At least we tried :man_shrugging:

**Comment by bakpakin** [comment] 2020-01-17 04:01
Closing for now, may reopen if the issue is relevant again (more traction on GitHub).

**Closed by bakpakin** 2020-01-17 04:01 UTC
