### ISSUE TITLE
Non deterministic behavior for deep= when used with tables or structs containing mutable keys

### ISSUE THREAD

**Issue by engenforge** [janet-lang/janet#1535] opened 2024-12-18 19:24 UTC
I was recently writing some tests for a janet project and came across some non-deterministic behavior where the test would fail randomly after running multiple times with no code modifications.

Below is a small code sample that demonstrates the behavior.  On my system the loop will iterate anywhere from 1 time to 30 times before breaking indicating that the two tables do not match.  This happens when any mutable structure (buffer, table, array) is used as a key and does not happen otherwise.
```
(loop [i :range [ 1 1000 ]]
  (if (not (deep= @{:key1 "value1" @"key2" "value2"}
                  @{:key1 "value1" @"key2" "value2"}))
    (break (print "Table with buffer key does not match in iteration " i))))
```
This was unexpected behavior for me as the two tables in the code snippet above are visually identical.  Is this a bug or is this expected behavior?

I did some further digging through the deep=, deep-not=, and kvs functions and the equality fails at random points due to the keys being in different order when doing the comparison.  I modified the kvs function [here](https://github.com/janet-lang/janet/blob/b16cf17246bc4d4b6508b8b8123d790ea33a4eed/src/boot/boot.janet#L1781) and the deep= comparison would then run in a deterministic manner (how I initially assumed it would run).

from:
`(loop [k :keys dict] (array/push ret k (in dict k)))`
to:
`(loop [k :in (sort (keys dict))] (array/push ret k (in dict k)))`

**Comment by sogaiu** [comment] 2024-12-19 04:08
With [this commit](9f4497a5ae9bf56a5704fa14c5bf950bcc50c0b7), I don't encounter the described discrepancy.

It is from [this commit](e2eb7ab4b2eae9be176bf11c0230f861cb1ffce5) that I start seeing differences.

**Comment by bakpakin** [comment] 2024-12-19 14:04
Using mutable data as a key is basically putting random pointers as keys, so what is happening is kvs returns keys in a random order.

Normally, structs with identical keys will have their internal layout be identical, so this is fine. But two different buffers will have different hashes regardless of their internal data, so `(deep-not= (kvs x) (kvs y))` may not always work.

Arguably, we might want to fix this, but using mutable data as a key is a bad idea for a lot of reasons. For example,
```janet
(get {@"key" :value} @"key") # evaluates to nil
```

Sorting keys will not help this either.

> With https://github.com/janet-lang/janet/commit/9f4497a5ae9bf56a5704fa14c5bf950bcc50c0b7, I don't encounter the described discrepancy.
> It is from https://github.com/janet-lang/janet/commit/e2eb7ab4b2eae9be176bf11c0230f861cb1ffce5 (the next commit) that I start seeing differences.

I don't think this is likely to be the culprit, possibly just a change that exposed this latent behavior.

**Comment by sogaiu** [comment] 2024-12-19 14:45
To support the point about the previously mentioned commit not being the culprit, if both keys are made mutable, even in a8c21459c310eb0cc882d8b6ce323bdf3b359cbb (2020-12-04), there appears to be a discrepancy.

```janet
(loop [i :range [1 1000]]
  (def a @{@"key1" "value1" @"key2" "value2"})
  (def b @{@"key1" "value1" @"key2" "value2"})
  (when (not (deep= a b))
    (print a)
    (pp a)
    (print b)
    (pp b)
    (break (print "Table with buffer key does not match in iteration " i))))
```

```
<table 0x55E69674EC20>
@{@"key2" "value2" @"key1" "value1"}
<table 0x55E69674ED50>
@{@"key1" "value1" @"key2" "value2"}
Table with buffer key does not match in iteration 3
```

I suppose it could be nice to support `deep=` working even in this type of case, but I don't think I'd be so enthusiastic with `deep=` getting (much?) slower for this.

**Comment by engenforge** [comment] 2024-12-19 17:34
Thank you both for the replies and thoughts.  So I'm realizing now there is more to this than the unexpected behavior from deep=.  I'm somewhat embarrassed to admit that I hadn't yet stumbled onto the issue that @bakpakin highlighted below.  It definitely would have cropped up for me soon in my code though so thank you for pointing that out.
```
(get {@"key" :value} @"key") # evaluates to nil
```
Long story short I plan to ensure in the project I'm working on that only immutable data types can be used as keys in a table or struct.

I agree that this is a niche corner case and that it wouldn't make sense to add a lot of extra overhead to the code base to address this.  With that said though I think at a minimum it would be good to update documentation to warn users about this.  I can put together a quick proposal / pull request for the website documentation if you want.

This [page](https://janet-lang.org/docs/data_structures/tables.html) currently states that 

> Any Janet value except nil and math/nan can be a key or a value in a Janet table, and a single Janet table can have any mixture of types as keys and values.

Adding a sentence or two pointing out that use of mutable keys will result in unexpected behavior would be good.

Also this [page](https://janet-lang.org/docs/comparison.html) says:

> To compare the contents of mutable structures use the deep= function. This function compares buffers like strings, and recursively compares arrays and tables.

Similarly it may be good to add a sentence or two stating that deep= will not work as expected when comparing tables or structs that use mutable keys.

Alternately or in addition the compiler could be updated to generate errors or warnings when code tries to use mutable keys.  It seems currently the only way to reliably retrieve data from tables or structs with mutable keys is to iterate though the key/value pairs using a loop?  If that's the case then it seems that there are much better ways to do that and there really isn't a use case for mutable keys?

**Comment by bakpakin** [comment] 2024-12-20 00:35
So there are still reasons to use mutable keys, it's not a bug per se, but just it probably isn't doing what you thing it's doing if you are calling deep= on two structures with two different mutable keys. We actually use mutable table keys in a few place in our test suite.

I have pushed a fix to deep= in 7f745a34c38fa6711a0846e3ccd7e8696e57df7b that will detect mutable table keys and try to handle those cases using `freeze`. This shouldn't be any slower in the common case and correctly handle our degenerate examples.

**Comment by engenforge** [comment] 2024-12-20 15:10
Thank you for making the updates, however shouldn't the following throw an assertion?
```
(assert (deep= @{:key1 "value1" @"key2" @"value2"}
               @{:key1 "value1" @"key2" "value2"}))
```

**Comment by bakpakin** [comment] 2024-12-21 14:46
Yes it should. After pushing my original changes, I have found many more edge cases here so I need to revisit this. I think it might be required to revert to a simpler behavior of having table and struct keys compared by value in deep= rather than recursive structures. Relying on `freeze` has the same problems that you have pointed out above.

**Comment by bakpakin** [comment] 2024-12-21 15:05
I've reverted some of the changes in 746ced55019d07f3de25e40ce6efb20dbd4ae95b - this compares table and struct keys by normal equality rules, side stepping a lot of issues. Most importantly, it should get rid of the dependence on iteration order we were seeing in the original implementation, which is the biggest issue IMO.

**Comment by engenforge** [comment] 2024-12-21 16:46
Sorry, I'm not understanding fully.  It seems that the test suite changed to make sure that any tables or structs with mutable keys will not be equal even if their contents are equal?
https://github.com/janet-lang/janet/commit/746ced55019d07f3de25e40ce6efb20dbd4ae95b#diff-faf55629d151fdeceb1ce33950b008c990fe29e99d8bff6d3263714ee2379435R1007

As you mentioned in the commit message for https://github.com/janet-lang/janet/commit/746ced55019d07f3de25e40ce6efb20dbd4ae95b mutable keys are a minefield, so my apologies if this issue that I raised is creating a lot of work for minimal value.

Your knowledge / skills on Janet are clearly well above mine, but if there are any aspects of this that I can take a stab at or help with, please let me know.

**Comment by bakpakin** [comment] 2024-12-21 17:43
Basically, equality of keys is now done (correctly) with `=` instead of (incorrectly) with `deep=`.

Examples:
```janet
(def k1 @"mutable-key")
(def k2 @"mutable-key") # a _different_ mutable key with the same buffer contents
(assert (deep= {k1 @"abc"} {k1 @"abc"}))
(assert (deep-not= {k2 @"abc"} {k1 @"abc"}))
```

**Comment by engenforge** [comment] 2024-12-21 18:43
Got it!  Thank you for the explanation, and thank you for making deep= deterministic.  I will go ahead and close this unless you think there's value in leaving this open.

**Closed** 2024-12-21 20:54 UTC
Labels: bug
