### ISSUE TITLE
Appveyor failures

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#397] opened 2020-05-13 23:12 UTC
Is there a reason they keep failing on every PR? Should we just disable them?

**Comment by bakpakin** [comment] 2020-05-14 01:06
The problem is the installer randomly times out when we try to run it and test that installation works. It is annoying but is not something I have been able to figure out. It also doesn't seem to repro on my windows machine. I've written it down to general appveyor/Windows/NSIS flakiness (maybe antivirus)?, but it happens far too often to be that. It does not seem to reproduce on my machine.

Some help on this would be nice - maybe an appveyor/NSIS/Windows expert could help with this. I am loathe to simply disable CI, though, as it is important that installation works correctly.

**Comment by bakpakin** [comment] 2020-05-14 01:08
Also, rerunning the jobs will eventually get them to pass. I have been scratching my head over this for a while, so if any one can tell me why this is happening and fix it I will get you a beer if we ever meet.

**Comment by leafgarland** [comment] 2020-05-15 02:16
I saw this issue, and wanted to explore github actions, so I added a workflow to replace appveyor. Unfortunately the installer hangs there too 😞.

**Comment by leafgarland** [comment] 2020-05-15 04:56
I stripped modern UI "MUI2" from the installer and no repeats of the hanging yet. But it is now a basic installer - instant install with progress bar basically.

**Comment by bakpakin** [comment] 2020-05-16 00:42
I think it started happening when I upgraded to NSIS 3.05 from 3.04 - so it may be a bug there, although I have a feeling that some dialog box is popping up, and since the install is "silent", it is being hidden. Just a theory

**Comment by leafgarland** [comment] 2020-05-17 12:52
Might seem a bit extreme but as I haven't yet tracked down what in the NSIS installer is causing the hang, I tried building a msi (via a wix script) instead.

So far, it is has not hung.

The installer is currently pretty basic, it only does per-user installs and has no fancy gui, just the basic msi progress bar, but the installed result is the same.

If you want to have a look you can get the installer from the appveyor artifacts [here](https://ci.appveyor.com/project/leafgarland/janet/build/job/oahnx0eu0t26wu1i/artifacts), and see the [diff](https://github.com/leafgarland/janet/commit/f71b2c706f8dedf440502a75229b4b6ec522c100).

I could improve the wix script to match what the NSIS installer (although wix/msi is a very strange world to operate in).

**Comment by bakpakin** [comment] 2020-05-17 12:57
Ok, this is great :)

I much prefer the Wix installer as NSIS has good docs but outdated design, and it is possible to really mess up a user’s system if not careful.

I would like to switch over to the Wix installer and I think it should be more robust in general. I do not know much about NSIS or Wix though. I think adding a system install would put it at pretty much parity with the current NSIS installer, I would just as want to get in CI to be generated for x64 and x86 on windows.

**Comment by leafgarland** [comment] 2020-05-17 13:37
All right, I will take a look at adding a system install option. My current changes are already creating x86/x64 installers (although I have not tested on a x86 system).

**Comment by bakpakin** [comment] 2020-05-20 03:28
Haven't seen any failures, tried the Windows installer, and things look good! Closing this for now.

**Closed by bakpakin** 2020-05-20 03:28 UTC
Labels: help wanted
