### ISSUE TITLE
Meson build libpath differs from make build libpath

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#419] opened 2020-05-31 21:31 UTC
I've got this report from someone building hermes with a meson built janet:

https://github.com/andrewchambers/hermes/issues/58

People with a make built janet did not seem to have this problem.

**Comment by steveno** [comment] 2020-06-02 01:38
Modifying the Meson instructions in the README to include `--libdir` will "fix" this.

```bash
meson setup build --buildtype release --optimization 2 --libdir /usr/local/lib -Dgit_hash=$(git log --pretty=format:'%h' -n 1)
```

**Comment by bakpakin** [comment] 2020-06-14 17:26
By default, `jpm` will guess that path to the janet libraries and headers based on the location of the janet binary that is executing the script. This is a bit of a hack that works fairly well on most installs, but is not a sliver bullet. It makes sense to hardcode those paths into the jpm script on install so that we don't need to guess and can correctly accommodate more configurations without needing environment variables.

**Comment by bakpakin** [comment] 2020-06-14 19:09
Should be addressed in 853b33b67caca3607d40e301a054d8bbecd26c1d, now default paths will be hardcoded into jpm on install (with both meson and Makefiles). This should not break installs and paths can still be overridden with environment variables and command line arguments.

**Closed by bakpakin** 2020-06-14 19:09 UTC

**Comment by pyrmont** [comment] 2020-06-16 05:19
@bakpakin This change breaks a GitHub Action I was using where I was extracting the compiled release for Linux and setting environment variables to set `JANET_HEADERPATH`, `JANET_LIBPATH` and `JANET_PATH` to be the directory with the extracted files.

The problem is that the install paths are calculated regardless of whether they're needed or not. Is it possible to use `defn` rather than `def`? That would I think mean the paths are only created if the script actually needs to use `install-paths`.

**Comment by pyrmont** [comment] 2020-06-16 05:21
Oh, and in case it helps: [the GitHub workflow](https://github.com/pyrmont/markable/blob/master/.github/workflows/build.yml) I'm using and [the log](https://github.com/pyrmont/markable/runs/775201422) of it failing.
