### ISSUE TITLE
One out of 30+ `make test` on macos fails

### ISSUE THREAD

**Issue by saikyun** [janet-lang/janet#816] opened 2021-09-24 10:21 UTC
https://github.com/saikyun/freja/runs/3698699684?check_suite_focus=true

This is on github actions macos-latest, which is: macOS 10.15

```
make test
...
✔ "peg empty pattern 6": true
✔ "simple number capture 1": true
✔ "simple number capture 2": true


Test suite 8 finished in 0.007 seconds
116 of 116 tests passed.


Running test suite 9 tests...
  
✔ "capture stdout from os/spawn pre close.": true
✔ "capture stdout from os/spawn post close.": true
make: *** [test] Error 141
Error: Process completed with exit code 2.
```

**Comment by llmII** [comment] 2021-09-24 10:50
This sort of goes along with #794 which I encountered during a pull request. I thought, at the time, I had accidentally truly broke it but it turns out it's a random, hard to encounter bug, that effects at least MacOS (if not *BSD). I'd note in my probably 400+ builds of Janet in the past few weeks I can't get it to happen on FreeBSD.

**Comment by bakpakin** [comment] 2021-09-25 17:13
Might be interesting to see if this depends on being built with epoll or not -  I expect the event machinery for MacOS is somehow slightly different that BSDs or Linux.

Also not sure if this is a race condition of some kind. I wonder if we could run that test suite in a loop with valgrind until it failed on mac. I've been having trouble testing on macos lately because my old macbook has been having battery issues.

**Comment by bakpakin** [comment] 2021-09-25 17:14
Closing as dupe of #794

**Closed by bakpakin** 2021-09-25 17:14 UTC
