### ISSUE TITLE
MacOS (maybe BSD's?) Random Suite 9 test failure @ Line 38

### ISSUE THREAD

**Issue by llmII** [janet-lang/janet#794] opened 2021-09-08 14:06 UTC
Errors are dealing with`os/spawn` and/or @ `calc-1` or `ev/gather`?

One of the test runs [here](https://github.com/llmII/janet/tree/feature-getsockname-getpeername) shows an example but since I don't have a MacOS device and haven't seen this under BSD I can't easily recreate the issue. Sort of needs someone to bang away at a Mac.

I don't think BSD has the issue (have run the test suite at least 100 times this past week on FreeBSD without encountering this error without it being due to new code I was writing/modifying/whatnot.

**Comment by llmII** [comment] 2021-09-30 12:08
This may be fixed via #823 - no way to know except to watch and see if CI pops the issue at Mac  over time. I'm not able to duplicate this under FreeBSD even running the suite 100x in a shell loop.

**Comment by hdcos** [comment] 2021-10-16 22:49
[janet-suite9.out.txt](https://github.com/janet-lang/janet/files/7358361/janet-suite9.out.txt)

i use a `for..do.done` in zsh with 100 then 1000 iterations
I have cleaned the output
it seems to have been successfull but maybe you will find an error message inside 
it has been painful to clean the output (so many useless print imho) it could be great to add a script to do this kind of for loop test and not having to do it by hand
it would be better to only print the tests that have failed (I guess)

**Comment by llmII** [comment] 2021-10-16 22:53
Looks like all passed to me!

**Comment by hdcos** [comment] 2021-10-16 22:57
yes I found 1200 `169 of 169 tests passed` occurrences
and I did 2x100 + 1000 iterations so I guess it's good

**Comment by bakpakin** [comment] 2021-10-17 01:28
Yeah, it is possible this bug has been fixed by a few fixes for other issue. I am going to close for now as cannot reproduce.

**Closed by bakpakin** 2021-10-17 01:28 UTC
Labels: bug
