### ISSUE TITLE
ffi/struct call leads to janet process termination

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1512] opened 2024-10-13 06:10 UTC
According to the [docs](https://janet-lang.org/docs/ffi.html#Primitive-Types):

> The void type can only be used as a return value

so, it makes sense that `(ffi/struct :void)` shouldn't work.

Currently though, the running `janet` process terminates:

```
$ janet
Janet 1.37.0-dev-282f2671 linux/x64/gcc - '(doc)' for help
repl:1:> (ffi/struct :void)
Floating point exception
$ echo $?
136
```

Is it practical to error without process termination instead?

**Comment by bakpakin** [comment] 2024-10-18 23:18
Yup, that is an issue - root cause is a division by zero when we are calculating size and alignment. Just pushed a fix, I think this reveals a bit of a hole in our FFI testing.

**Closed** 2024-10-18 23:18 UTC
Labels: bug
